### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by nitrogithub** [nitrogithub/photogramSwift#1]
atousa to setup relationships:
1. User object / entity
2. Picture object / entity

**Comment by nitrogithub** [comment]
- Core Data Fields:
  User Entity
  Username
  profileImage
  Gender?
  Relationship
  Comments
  Image
- Image Entity
  Name
  Timestamp
  Location
  comment
  isSelected
  Relationship
  Username
  Comment
- Comment Entity
  Comments
  Timestamp
  Relationship
  Username
  Image

**Comment by Atousa** [comment]
Pushed first version of model to branch atousa

**Comment by Atousa** [comment]
has been pushed in the master last night,
